import 'package:first_task_app/frontend/navigation/index.dart';

class Routes {
  Routes._();

  static const String welcome = '/';
  static const String signup = '/personal';
  static const String setPassword = '/setPassword';
  static const String login = '/login';
  static const String resetPassword = '/resetPassword';
  static const String companyVerification = '/organization';
  static const String universityVerification = '/university';
  static const String uniSignUp = '/uniSignUp';
  static const String companySignUp = '/companySignUp';
  static const String primary = '/primary';
  static const String home = '/home';
  static const String physicalActivity = '/physicalActivity';
  static const String loading = '/loading';
  static const String assessment = '/assessment';
  static const String m2mood = '/m2mood';
  static const String m3primary = '/m3primary';
  static const String m4copping = '/m4copping';
  static const String m5support = '/m5support';
  static const String m2sleep = '/m2sleep';
  static const String stress = '/stress';
  static const String stresslocation = '/stresslocation';
  static const String stresschallenge = '/stresschallenge';
  static const String learningPreference = '/learningPreference';
  static const String m4opensharing = '/m4opensharing';
  static const String insights = '/insights';
  static const String m4processing = '/m4processing';
  static const String m2mindfulness = '/m2mindfulness';
  static const String m4weekly = '/m4weekly';
  static const String posh1 = '/posh1';
  static const String poshpolicy = '/poshpolicy';
  static const String poshpolicy8 = '/poshpolicy8';
  static const String poshpolicy9 = '/poshpolicy9';
  static const String poshpolicy10 = '/poshpolicy10';
  static const String poshpolicy11 = '/poshpolicy11';
  static const String poshpolicy12 = '/poshpolicy12';
  static const String reportcompliant = '/reportcompliant';
  static const String compliantconfirmation = '/compliantconfirmation';
  static const String poshcompliant5 = '/poshcomplian5';
  static const String poshcompliant51 = '/poshcomplian51';
  static const String poshcompliant52 = '/poshcomplian52';
  static const String help1 = '/help1';
  static const String help2 = '/help2';
  static const String help3 = '/help3';
  static const String help4 = '/help4';
  static const String help5 = '/help5';
  static const String help6 = '/help6';
  static const String compliantloading = '/compliantloading';
  static const String compliantsucess = '/compliantsuccess';
  static const String complianttracking = '/complianttracking';
  static const String uniassessment = '/uniassessment';
 static const String uniassessment1 = '/uniassessment1';
 static const String uniassessment2 = '/uniassessment2';
 static const String uniassessment3 = '/uniassessment3';
 static const String uniassessment4 = '/uniassessment4';
 static const String uniassessment5 = '/uniassessment5';
 static const String uniassessment6 = '/uniassessment6';
  static const String uniassessment7 = '/uniassessment7';
 static const String uniassessment8 = '/uniassessment8';
 static const String uniassessment9 = '/uniassessment9';
 static const String uniassessment10 = '/uniassessment10';
 static const String uniassessment11 = '/uniassessment11';
 static const String uniassessment12 = '/uniassessment12';
 static const String uniassessment13 = '/uniassessment13';

}
